# Generated by Django 3.2.19 on 2023-06-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osidb', '0075_flawreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='flawcomment',
            name='_alerts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='flawcomment',
            name='external_system_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='flawcomment',
            constraint=models.UniqueConstraint(fields=('flaw', 'order'), name='unique_per_flaw_comment_nums'),
        ),
    ]
